# Generated by Django 4.1.2 on 2022-12-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('apId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('apName', models.TextField(max_length=255)),
                ('place', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brId', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('brName', models.CharField(choices=[('VJ', 'Vietjet'), ('VN', 'Vietnam'), ('BB', 'Bamboo'), ('PA', 'Philippine'), ('JP', 'Japan')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flId', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('flTime', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.brand')),
                ('fromAp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromAP_flight', to='flights.airport')),
                ('toAp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toAP_flight', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('flId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flights.flight')),
                ('date', models.DateField()),
                ('firstClassBooked', models.IntegerField()),
                ('secondClassBooked', models.IntegerField()),
                ('firstClass', models.IntegerField()),
                ('secondClass', models.IntegerField()),
            ],
            options={
                'unique_together': {('flId', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketId', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('customID', models.TextField()),
                ('booked', models.DateTimeField(auto_now=True)),
                ('cost', models.FloatField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_ticket', to='flights.schedule')),
                ('flId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flId_ticket', to='flights.schedule')),
            ],
        ),
    ]
